<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Checkout\Block\Cart\Sidebar */
?>
                      
<li>                      
<!-- <div data-block="minicart" class="minicart-wrapper"> -->
    <a class="action l-minicart" data-block="mobile_minicart" href="<?php /* @escapeNotVerified */ echo $block->getShoppingCartUrl(); ?>"
       data-bind="scope: 'minicart_content'">
       <svg class="l-icon" width="12" height="12">
<use xlink:href="<?php echo $this->getViewFileUrl('images/icons-svg.svg#shopping-cart'); ?>"></use>
</svg>
        <span class="text"><?php /* @escapeNotVerified */ echo __('Mijn winkelwagen'); ?></span>
        <span class="counter qty empty"
              data-bind="css: { empty: !!getCartParam('summary_count') == false }, blockLoader: isLoading">
            
            <!-- <span class="counter-number"> -->
            <!-- ko text: getCartParam('summary_count') --><!-- /ko -->                
            <!-- </span> -->

            
        </span>
    </a>    
<!-- </div> -->

</li>
</ul>
<!-- </div>
</div> -->
