<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Checkout\Block\Cart\Sidebar */
?>
<!-- <a class="l-minicart" href="#">
                  <svg class="l-icon" width="26" height="26">
                    <use xlink:href="<?php echo $this->getViewFileUrl('images/icons-svg.svg#shopping-cart'); ?>"></use>
                  </svg></a> -->
                      
                  
<!-- <div data-block="mobile_minicart" class="minicart-wrapper"> -->
    <a class="action l-minicart" data-block="mobile_minicart" href="<?php /* @escapeNotVerified */ echo $block->getShoppingCartUrl(); ?>"
       data-bind="scope: 'minicart_content'">
       <svg class="l-icon" width="26" height="26">
<use xlink:href="<?php echo $this->getViewFileUrl('images/icons-svg.svg#shopping-cart'); ?>"></use>
</svg>
       
        <span class="counter qty empty"
              data-bind="css: { empty: !!getCartParam('summary_count') == false }, blockLoader: isLoading">
            
            <!-- <span class="counter-number"> -->
            <!-- ko text: getCartParam('summary_count') --><!-- /ko -->                
            <!-- </span> -->

        </span>
    </a>
    <?php if ($block->getIsNeedToDisplaySideBar()): ?>
        <div class="block block-minicart empty"
             data-role="dropdownDialog"
             data-mage-init='{"dropdownDialog":{
                "appendTo":"[data-block=mobile_minicart]",
                "triggerTarget":".l-minicart",
                "timeout": "2000",
                "closeOnMouseLeave": false,
                "closeOnEscape": true,
                "triggerClass":"active",
                "parentClass":"active",
                "buttons":[]}}'>
            <div id="minicart-content-wrapper" data-bind="scope: 'mobile_minicart_content'">
                <!-- ko template: getTemplate() --><!-- /ko -->
            </div>
            <?php echo $block->getChildHtml('minicart.addons'); ?>
        </div>
    <?php endif ?>
    <script>
        window.checkout = <?php /* @escapeNotVerified */ echo \Zend_Json::encode($block->getConfig()); ?>;
    </script>
    <script type="text/x-magento-init">
    {
        "[data-block='minicart']": {
            "Magento_Ui/js/core/app": <?php /* @escapeNotVerified */ echo $block->getJsLayout();?>
        },
        "*": {
            "Magento_Ui/js/block-loader": "<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/loader-1.gif'); ?>"
        }
    }
    </script>
<!-- </div> -->