<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Checkout\Block\Cart\Sidebar */
?>
<a class="l-minicart" href="#">
                  <svg class="l-icon" width="26" height="26">
                    <use xlink:href="<?php echo $this->getViewFileUrl('images/icons-svg.svg#shopping-cart'); ?>"></use>
                  </svg></a>
                      
