<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Checkout\Block\Cart\Sidebar */
?>
<!-- <a class="l-minicart" href="#">
                  <svg class="l-icon" width="26" height="26">
                    <use xlink:href="<?php echo $this->getViewFileUrl('images/icons-svg.svg#shopping-cart'); ?>"></use>
                  </svg></a> -->
                      
                  
<!-- <div data-block="minicart" class="minicart-wrapper"> -->
    <a class="action l-minicart"  data-block="minicart" href="<?php /* @escapeNotVerified */ echo $block->getShoppingCartUrl(); ?>"
       data-bind="scope: 'minicart_content'">
       <svg class="l-icon" width="26" height="26">
<use xlink:href="<?php echo $this->getViewFileUrl('images/icons-svg.svg#shopping-cart'); ?>"></use>
</svg>
       
        <span class="counter qty empty"
              data-bind="css: { empty: !!getCartParam('summary_count') == false }, blockLoader: isLoading">
            
            <!-- <span class="counter-number"> -->
            <!-- ko text: getCartParam('summary_count') --><!-- /ko -->                
            <!-- </span> -->

        </span>
    </a>    
<!-- </div> -->