<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * Grouped product data template
 *
 * @var $block \Magento\Catalog\Block\Product\View\BaseImage
 * @var $block \Magento\GroupedProduct\Block\Product\View\Type\Grouped
 */
?>
<?php $block->setPreconfiguredValue(); ?>
<?php $_product = $block->getProduct(); ?>
<?php $_associatedProducts = $block->getAssociatedProducts(); ?>
<?php $_hasAssociatedProducts = count($_associatedProducts) > 0; ?>

<ul class="cart__group">

        <?php if ($_hasAssociatedProducts): ?>
        <?php foreach ($_associatedProducts as $_item): ?>
<li>
<?php

$pid = $_item->getId(); 
$imagewidth = 500;
$imageheight = 500;
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$_product = $objectManager->get('Magento\Catalog\Model\Product')->load($pid);
$imageHelper  = $objectManager->get('\Magento\Catalog\Helper\Image');
$productImage = $imageHelper->init($_product, 'product_page_image_small')->setImageFile($_product->getFile())->resize($imagewidth, $imageheight)->getUrl();

?>
<div class="cart__group-container"> 
<div class="cart__group-wrapper">
<figure>
<?php
if($productImage != '')
{
?>
<img src="<?php echo $productImage; ?>" alt="<?php echo $block->escapeHtml($_item->getName()) ?>" />
<?php 
}else{
    ?>
<img src="<?php echo $block->getViewFileUrl('images/product_thumb_01.jpg'); ?>" alt="<?php echo $block->escapeHtml($_item->getName()) ?>" />    
    <?php
}
?>
</figure>
<div class="cart__product-wrapper">
<h4 class="cart__product"><a href="#"><?php echo $block->escapeHtml($_item->getName()); ?>
</a></h4>
<div class="cart__additionalinfo"><span><?php echo $block->escapeHtml($_item->getSku()); ?></span><span><?php echo $block->escapeHtml($_item->getSku()); ?></span></div>
</div>
</div>
<div class="cart__product-price"><span>
  <?php //if ($block->getCanShowProductPrice($_product)): ?>
                        <?php //if ($block->getCanShowProductPrice($_item)): ?>
                            <?php /* @escapeNotVerified */ echo $block->getProductPrice($_item) ?>
                        <?php //endif; ?>
                     <?php //endif; ?>
</span></div>

<input class="cart__quantity" type="number" name="quantity" min="1" max="5" value="1">
</div>
</li>
        <?php endforeach; ?>
        <?php else: ?>		
		<li>
<div class="cart__group-container"> 
<div class="cart__group-wrapper">
<figure><img src="" alt="product thumb 01"></figure>
<div class="cart__product-wrapper">
<h4 class="cart__product"><a href="#">  <?php /* @escapeNotVerified */ echo __('No options of this product are available.') ?></a></h4>
<div class="cart__additionalinfo"><span></span><span></span></div>
</div>
</div>
<div class="cart__product-price"><span></span></div>
<form>
</form>
</div>
</li>
        <?php endif; ?>
</ul>


