<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var \Magento\Theme\Block\Html\Header\Logo $block
 */
?>

<?php $storeName = $block->getThemeName() ? $block->getThemeName() : $block->getLogoAlt();?>

<h1 class="logo">
<a class="" href="<?php echo $block->getUrl(''); ?>" title="<?php /* @escapeNotVerified */ echo $storeName ?>">
<!-- <img src="images/logo.png" alt="Dental union" title="Dental union"/> -->
<img src="<?php echo $block->getLogoSrc() ?>"/>	
</a>
</h1>
<?php 
if ($block->isHomePage()) {
    ?>
	<style type="text/css">
	main.page-main
	{
		max-width:100% !important;
	}
	
	</style>

	<?php
}
?>