<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /* @escapeNotVerified */ //echo $block->getMiscellaneousHtml();
?>


<script  type="text/javascript"  src="<?php echo $this->getViewFileUrl('js/plugin.bundle.js'); ?>"></script>
<script  type="text/javascript"  src="<?php echo $this->getViewFileUrl('js/script.bundle.js'); ?>"></script>