<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php if ($crumbs && is_array($crumbs)) : ?>
<div class="row">
            <div class="col-sm-12">
              <div class="l-breadcrumb">
                <ul>
                <?php foreach ($crumbs as $crumbName => $crumbInfo) : ?>
                <li class="<?php /* @escapeNotVerified */ echo $crumbName ?>">
            <?php if ($crumbInfo['link']) : ?>
                <a href="<?php /* @escapeNotVerified */ echo $crumbInfo['link'] ?>" title="<?php echo $block->escapeHtml($crumbInfo['title']) ?>">
                <span><?php echo $block->escapeHtml($crumbInfo['label']) ?></span>
                </a>
            <?php elseif ($crumbInfo['last']) : ?>
                <strong><?php echo $block->escapeHtml($crumbInfo['label']) ?></strong>
            <?php else: ?>
                <?php echo $block->escapeHtml($crumbInfo['label']) ?>
            <?php endif; ?>
            </li>   
                    
                  <li><a href="#"><span>home</span></a></li>
                  <?php endforeach; ?>
                </ul>
              </div>
            </div>
          </div>
<?php endif; ?>

