<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>


        <div class="footer-copyright">
          <div class="container">
            <div class="row">
              <div class="col-xs-12">
                <p class="footer-by">
                <?php echo $block->getMiscellaneousHtml(); ?>
                </p>
                <p>                
                <?php echo $block->getCopyright(); ?>
                </p>
              </div>
            </div>
          </div>
        </div>

</body>
</html>