
          <div class="navigation">
            <div class="container">
              <div class="row">
                <div class="col-md-9 col-md-offset-3">
                  <div class="nav-main">
                    <ul>
                      <li class="active"><a href="#">Verbruiksmaterialen      </a>
                        <ul class="is-submenu level-first">
                          <li><a href="#">Category one  </a>
                            <ul class="is-submenu level-second">
                              <li><a href="#">Group one</a>
                                <ul class="is-submenu level-third">
                                  <li><a href="#">Item one                           </a></li>
                                  <li><a href="#">Item two                           </a></li>
                                  <li><a href="#">Item three                           </a></li>
                                  <li><a href="#">Item four                              </a></li>
                                </ul>
                              </li>
                              <li><a href="#">Group two                           </a></li>
                              <li><a href="#">Group three                           </a></li>
                              <li><a href="#">Group four                    </a></li>
                            </ul>
                          </li>
                          <li><a href="#">Category two                           </a></li>
                          <li><a href="#">Category three                     </a></li>
                          <li><a href="#">Category four           </a></li>
                        </ul>
                      </li>
                      <li><a href="#">Elementen</a></li>
                      <li><a href="#">Apparatuur & onderdelen </a></li>
                      <li><a href="#">plandent college</a></li>
                      <li><a href="#">aanbiedingen</a>
                        <ul class="is-submenu level-first">
                          <li><a href="#">Category one  </a>
                            <ul class="is-submenu level-second">
                              <li><a href="#">Group one</a>
                                <ul class="is-submenu level-third">
                                  <li><a href="#">Item one                           </a></li>
                                  <li><a href="#">Item two                           </a></li>
                                  <li><a href="#">Item three                           </a></li>
                                  <li><a href="#">Item four                              </a></li>
                                </ul>
                              </li>
                              <li><a href="#">Group two                           </a></li>
                              <li><a href="#">Group three                           </a></li>
                              <li><a href="#">Group four                    </a></li>
                            </ul>
                          </li>
                          <li><a href="#">Category two                           </a></li>
                          <li><a href="#">Category three                     </a></li>
                          <li><a href="#">Category four                            </a></li>
                        </ul>
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>


 <!-- <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>  -->
<script  type="text/javascript"  src="<?php echo $this->getViewFileUrl('js/plugin.bundle.js'); ?>"></script>
<script  type="text/javascript"  src="<?php echo $this->getViewFileUrl('js/script.bundle.js'); ?>"></script>
 