<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var $block \Magento\Theme\Block\Html\Title
 */
$cssClass = $block->getCssClass() ? ' ' . $block->getCssClass() : '';



$title = '';
if (trim($block->getPageHeading())) {
    $title = '<span class="base" data-ui-id="page-title-wrapper" ' .  $block->getAddBaseAttribute() . '>'
        . $block->escapeHtml($block->getPageHeading()) . '</span>';
}
?>

<?php

if($block->getAddBaseAttributeAria() == 'page-title-heading toolbar-amount')
{
?>

<section class="spotlight spotlight--category">
          <div class="spotlight__image"><img src="<?php echo $this->getViewFileUrl('images/temp/spotlight_img_01.jpg'); ?>" alt="" style="width:2000px;height:150px;">
            <h2 class="l-page-title"><?php echo strip_tags($title); ?></h2>
          </div>
</section>

<?php
}else{

 if ($title): 
    
    if(trim($cssClass) == 'product')
    {
        ?>
    <h2 class="cart__title">        
        <?php /* @escapeNotVerified */ echo strip_tags($title); ?>
    </h2>    
        <?php
    }else{ 
    ?>
<div class="page-title-wrapper<?php /* @escapeNotVerified */ echo $cssClass; ?>">
    <h1 class="page-title"
        <?php if ($block->getId()): ?> id="<?php /* @escapeNotVerified */ echo $block->getId();?>" <?php endif; ?>
        <?php if ($block->getAddBaseAttributeAria()): ?>
            aria-labelledby="<?php /* @escapeNotVerified */ echo $block->getAddBaseAttributeAria(); ?>"
        <?php endif; ?>>
        <?php /* @escapeNotVerified */ echo $title ?>
    </h1>
    <?php echo $block->getChildHtml(); ?>
</div>
<?php 
    }
endif; 
}
?>
