<?php ?>

                  <nav class="nav-links">
                    <ul>
                      <li><a class="active" href="#">
                          <svg class="l-icon" width="12" height="12">
                            <use xlink:href="images/icons-svg.svg#phone"></use>
                          </svg><span>Contact</span></a></li>
                      <li><a href="#">
                          <svg class="l-icon" width="12" height="12">
                            <use xlink:href="images/icons-svg.svg#user"></use>
                          </svg><span>Mijn account</span></a></li>
                      <li><a href="#">
                          <svg class="l-icon" width="12" height="12">
                            <use xlink:href="images/icons-svg.svg#star-o"></use>
                          </svg><span>Favorieten</span></a></li>
                      <li><a href="#"> 
                          <svg class="l-icon" width="12" height="12">
                            <use xlink:href="images/icons-svg.svg#barcode"></use>
                          </svg><span>Barcodes</span></a></li>
                      <li><a class="l-minicart" href="#">
                          <svg class="l-icon" width="12" height="12">
                            <use xlink:href="images/icons-svg.svg#shopping-cart"></use>
                          </svg><span>Mijn winkelwagen</span></a></li>
                    </ul>
                  </nav>
                </div>
              </div>
            </div>
          </div>