<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Top menu for store
 *
 * @var $block \Magento\Theme\Block\Html\Topmenu
 */
?>
<?php $columnsLimit = $block->getColumnsLimit() ?: 0; ?>
<?php $_menu = $block->getHtml('level-top', 'submenu', $columnsLimit) ?>
          <div class="site-navigation">
            <div class="container">
              <div class="row">
                <div class="col-md-9 col-md-offset-3">
                  <div class="nav-main">
				<ul class="">
				<?php /* @escapeNotVerified */ echo $_menu; ?>
				<?php /* @escapeNotVerified */ echo $block->getChildHtml(); ?>
				</ul>
                  </div>
                </div>
              </div>
            </div>
          </div>

