<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Top menu for store
 *
 * @var $block \Magento\Theme\Block\Html\Topmenu
 */
?>
<?php $columnsLimit = $block->getColumnsLimit() ?: 0; ?>
<?php $_menu = $block->getHtml('level-top', 'submenu', $columnsLimit) ?>

<!--<nav class="navigation" data-action="navigation">-->

<!--</nav>-->
<style type="text/css">
.page-header .mobile-wrapper .global-search {
    display: inline-block;
    fill: #003f79;
    float: right;
    margin: 15px 15px 0 0
}

@media (min-width:992px) {
    .page-header .mobile-wrapper .global-search {
        position: absolute;
        right: 0;
        top: 62px;
        fill: #fff;
        z-index: 99
    }
}

@media (min-width:992px) {
    .page-header .mobile-wrapper .global-search .l-icon {
        width: 16px;
        height: 16px
    }
}
@media only screen and (max-width: 980px)
{
.navigation {
    background: none !important;
    box-sizing: border-box;
}
}

.l-minicart-mobile
{
  display: none !important;
}

@media only screen and (max-width: 980px)
{
  .l-minicart-mobile
  {
    display: block !important;
    display: inline-block;
    fill: #003f79;
    float: right;
    margin: 15px 15px 0 0;
  }

}

</style>

          <div class="navigation">
            <div class="container">
              <div class="row">
                <div class="col-md-9 col-md-offset-3">
                  <div class="nav-main">
				<ul class="" data-mage-init='{"menu":{"responsive":true, "expanded":true, "position":{"my":"left top","at":"left bottom"}}}'>
				<?php /* @escapeNotVerified */ echo $_menu; ?>
				<?php /* @escapeNotVerified */ //echo $block->getChildHtml(); ?>
				</ul>
                  </div>
                </div>
              </div>
            </div>
          </div>
        


