<?php
    $_helper    = $this->helper('Magento\Catalog\Helper\Output');
    $_category  = $block->getCurrentCategory();
    $_imgHtml   = '';
    //if ($_imgUrl = $_category->getImageUrl()) {
       // $_imgHtml = '<div class="category-image"><img src="' . $_imgUrl . '" alt="' . $block->escapeHtml($_category->getName()) . '" title="' . $block->escapeHtml($_category->getName()) . '" class="image" /></div>';
        //$_imgHtml = $_helper->categoryAttribute($_category, $_imgHtml, 'image');
        /* @escapeNotVerified */ 
    //}
//$this->getViewFileUrl('images/temp/spotlight_img_01.jpg');
    if ($_imgUrl = $_category->getImageUrl()) {
?>

<section class="spotlight spotlight--category">
          <div class="spotlight__image"><img src="<?php echo  $_imgUrl; ?>" alt="" style="width:1800px;height:150px;">
            <h2 class="l-page-title"><?php echo $block->escapeHtml($_category->getName()); ?></h2>
          </div>          
</section>
<?php
}else{
?>
<section class="spotlight spotlight--category">
          <div class="spotlight__image"><img src="<?php echo  $this->getViewFileUrl('images/temp/spotlight_img_01.jpg'); ?>" alt="" style="width:1800px;height:150px;">
            <h2 class="l-page-title"><?php echo $block->escapeHtml($_category->getName()); ?></h2>
          </div>          
</section>

<?php
}
?>