<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Template for displaying products list widget
 *
 * @var $block \Magento\CatalogWidget\Block\Product\ProductsList
 */
?>
<?php if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())):?>
<?php
    $type = 'widget-product-grid';

    $mode = 'grid';

    $image = 'new_products_content_widget_grid';
    $title = $block->getTitle() ? __($block->getTitle()) : '';
    $items = $block->getProductCollection()->getItems();

    $showWishlist = true;
    $showCompare = true;
    $showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::DEFAULT_VIEW;
    $description = false;
?>

<section class="section section--products">
          <div class="container">
            <div class="row">
              <div class="col-sm-12">
              <?php 
              if($title == 'Bulkvoordel')
              {
                ?>
                <div class="products products--bulk">
                <?php

              }
              if($title == 'Budget Line')
              {
                ?>
                <div class="products products--budget">
                <?php

              }
              if($title == 'Weekacties')
              {
                ?>
                <div class="products">
                <?php

              }
              ?>                
        <?php if ($title):?>        
        <h2 class="l-title"><?php /* @escapeNotVerified */ echo $title; ?></h2>
        
        
        <?php 
              if($title == 'Bulkvoordel')
              {
                ?>
              <span class="l-tagline">PAK JE VOORDEEL...</span>
                <?php

              }
              if($title == 'Budget Line')
              {
                ?>
                <span class="l-tagline">GOED MAAR TOCH GOEDKOOP...</span>
                <?php

              }
              if($title == 'Weekacties')
              {
                ?>
             <span class="l-tagline">SPECIAAL GESELECTEERD...</span>
                <?php

              }
              ?>
        <?php endif ?>
        <ul class="products__list">
                    <?php $iterator = 1; ?>
                    <?php foreach ($items as $_item): ?>
                        <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="">' : '</li><li class="">' ?>
                         <div class="products__holder">
                  
                            <figure>
                          
                                <?php echo $block->getImage($_item, $image)->toHtml(); ?>
                       
                            </figure>
                            <hr>
                   
                                <h3 class="products__name">
                                       <a href="<?php echo $block->getProductUrl($_item); ?>">
                                        <?php echo $block->escapeHtml($_item->getName()) ?>
                                        </a>                                    
                                   </h3> 
                   
                                <?php
                                echo $block->getProductPriceHtml($_item, $type);
                                ?>

                                <?php if ($templateType): ?>
                                    <?php echo $block->getReviewsSummaryHtml($_item, $templateType) ?>
                                <?php endif; ?>

                                <?php if ($showWishlist || $showCompare || $showCart): ?>
                        
                                        <?php if ($showCart): ?>
              
                                                <?php if ($_item->isSaleable()): ?>
                                                    <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
                                                        <a class="l-btn" href="<?php echo $block->getAddToCartUrl($_item) ?>">
                                                            <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                                        </a>
                                                    <?php else: ?>
                                                        <?php
                                                            $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                                            $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
                                                        ?>
                                                        <a class="l-btn" href="#"
                                                                data-post='<?php /* @escapeNotVerified */ echo $postData; ?>'
                                                                type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                                            <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                                        </a>
                                                    <?php endif; ?>
                                                <?php else: ?>
                                                    <?php if ($_item->getIsSalable()): ?>
                                                        <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                                    <?php else: ?>
                                                        <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                                    <?php endif; ?>
                                                <?php endif; ?>

                                        <?php endif; ?>
                                        <?php if ($showWishlist || $showCompare): ?>
                                         
                                        <?php endif; ?>
 
                                <?php endif; ?>

                        <?php echo($iterator == count($items)+1) ? '</li>' : '' ?>
                    <?php endforeach ?>

            <?php echo $block->getPagerHtml() ?>
            </div>

        </ul>

        </div></div></div></div>
        </section>
    <!-- </div> -->
<?php endif;?>
