<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()): ?>

<style type="text/css">
.cart .cart__form-group {
    margin-bottom: 15px;
    width: 35%;
    float: left;
}
button#product-addtocart-button
{
    float: right;
}
    h3{
    font-size: 24px !important;
    font-family: Lato,sans-serif;
    }
</style>


  <div class="cart__footer">
                  <form class="cart__form">
                    <div class="cart__form-group">
                      <label class="cart__input-label">AANTAI</label>                        
                          <?php if ($block->shouldRenderQuantity()): ?>
                        <input class="cart__quantity" type="number" name="qty" min="1" max="22" value="<?php /* @escapeNotVerified */ echo $block->getProductDefaultQty() * 1 ?>" data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>">
                         <?php endif; ?>
                    </div>
                    <!-- <input class="l-btn" type="button" value="in winkelmandje"> -->
                    <button type="submit"
                    title="<?php /* @escapeNotVerified */ echo $buttonTitle ?>"
                    class="l-btn tocart"
                    id="product-addtocart-button">
                <span><?php /* @escapeNotVerified */ echo $buttonTitle ?></span>
            </button>
                  </form>
                </div>


<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/product/view/validation": {
                "radioCheckboxClosest": ".nested"
            }
        }
    }
</script>
<?php if (!$block->isRedirectToCartEnabled()) : ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "catalogAddToCart": {
                "bindSubmit": false
            }
        }
    }
</script>
<?php endif; ?>
