<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * Product additional attributes template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Attributes
 */
?>
<?php
    $_helper = $this->helper('Magento\Catalog\Helper\Output');
    $_product = $block->getProduct();


?>


<?php if ($_additional = $block->getAdditionalData()): ?>
          <div class="row">
            <div class="col-sm-12">
              <section class="section section--generic section--generic-details">
                <div class="generic">
                  <h3 class="l-title">Extra<span>informatie</span></h3>
                  <ul class="generic__list">
                  <?php //echo $html_1; ?>
                      <?php foreach ($_additional as $_data): ?>
                    <li> <span class="generic__label"><?php echo $block->escapeHtml(__($_data['label'])) ?></span>
                    <span class="generic__value"><?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_data['value'], $_data['code']) ?> </span></li>

                  <?php endforeach; ?>
                  </ul>
                </div>
              </section>
            </div>
          </div>
          <?php endif;?>