<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php $detailedInfoGroup = $block->getGroupChildNames('detailed_info', 'getChildHtml');
$layout = $block->getLayout(); 
$html = $layout->renderElement($detailedInfoGroup[0]);
$html_1 = $layout->renderElement($detailedInfoGroup[1]);

?>      
         <div class="row">
            <div class="col-sm-12">
              <section class="section section--generic section--generic-details">
                <div class="generic">
                  <article>
                    <h3 class="l-title">product<span>omschrijving</span></h3>
                    <?php echo $html; ?>
                  </article>
                </div>
              </section>
            </div>
          </div>
           <?php echo $html_1; ?>